AllCops:
  Exclude:
    - db/schema.rb
    - 'vendor/**/*'
    - 'db/migrate/*'
    - 'lib/tensorflow/core/example/*.rb'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 100
